public with sharing class BroadsignBo {
	public BroadsignBo(){}
	public String avVersion {get;set;}
	public String clockSkew {get;set;}
	public String currentLocation {get;set;}
	public String currentlyDownloading {get;set;}
	public String currentlyPlaying {get;set;}
	public String currentVolume {get;set;}
	public String displayUnitId {get;set;}
	public String issue {get;set;}
	public String lastPoll {get;set;}
	public String localTime {get;set;}
	public String loopx {get;set;}
	public String name {get;set;}
	public String nextAdToDownload {get;set;}
	public String nextPoll {get;set;}
	public String playerId {get;set;}
	public String playerVersion {get;set;}
	public String screenResolution {get;set;}
	public String status {get;set;}
}